title: Mathematics for Machine Learning
author: johnmgiorgi
email: johnmgiorgi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A set of notes, in the form of a simple Github Pages site, which will serve as a
  complete crash course on the various areas of mathematics essential to understanding
  machine learning.

# social links
# twitter_username: your-twitter-handle
github_username: JohnGiorgi

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima

# adds mathjax support
mathjax: true
