# Project information
site_name: Mathematics for Machine Learning
site_author: 'John Giorgi'
site_url: 'https://johngiorgi.github.io/mathematics-for-machine-learning/'

# Repository
repo_name: 'JohnGiorgi/mathematics-for-machine-learning'
repo_url: 'https://github.com/JohnGiorgi/mathematics-for-machine-learning'

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'blue'
    accent: 'blue'

# Customization
extra:
  social:
    - type: 'github'
      link: 'https://github.com/JohnGiorgi'

extra_css:
  - 'stylesheets/extra.css'

extra_javascript:
  # - 'javascripts/vanilla-tilt.min.js'
  # Add MathJax support

  - 'javascripts/extra.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  - 'https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/tilt.js/1.2.1/tilt.jquery.min.js'

# Navigation
nav:
    - About: index.md
    - Linear Algebra:
        - Course Resources: linear_algebra/course_resources.md
        - Week 1: linear_algebra/week_1.md
        - Week 2: linear_algebra/week_2.md
        - Week 3: linear_algebra/week_3.md
        - Week 4: linear_algebra/week_4.md
        - Week 5: linear_algebra/week_5.md
    - Multivariate Calculus:
      - Course Resources: multivariate_calculus/course_resources.md
      - Week 1: multivariate_calculus/week_1.md

markdown_extensions:
    - pymdownx.arithmatex
    - pymdownx.details
    - pymdownx.superfences
    - admonition
