site_name: Mathematics for Machine Learning

nav:
    - About: index.md
    - Linear Algebra: linear_algebra.md
    - Calculus: calculus.md

theme:
  name: 'material'

# Add MathJax support
extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
    - mdx_math
